#
#   TOPPERS/ASP Kernel
#       Toyohashi Open Platform for Embedded Real-Time Systems/
#       Advanced Standard Profile Kernel
#
#   Copyright (C) 2000-2003 by Embedded and Real-Time Systems Laboratory
#                               Toyohashi Univ. of Technology, JAPAN
#   Copyright (C) 2003-2008 by Ryosuke Takeuchi
#                Platform Development Center RICOH COMPANY,LTD. JAPAN
#
#   上記著作権者は，以下の (1)〜(4) の条件か，Free Software Foundation 
#   によって公表されている GNU General Public License の Version 2 に記
#   述されている条件を満たす場合に限り，本ソフトウェア（本ソフトウェア
#   を改変したものを含む．以下同じ）を使用・複製・改変・再配布（以下，
#   利用と呼ぶ）することを無償で許諾する．
#   (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#       権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#       スコード中に含まれていること．
#   (2) 本ソフトウェアを，ライブラリ形式など，他のソフトウェア開発に使
#       用できる形で再配布する場合には，再配布に伴うドキュメント（利用
#       者マニュアルなど）に，上記の著作権表示，この利用条件および下記
#       の無保証規定を掲載すること．
#   (3) 本ソフトウェアを，機器に組み込むなど，他のソフトウェア開発に使
#       用できない形で再配布する場合には，次のいずれかの条件を満たすこ
#       と．
#     (a) 再配布に伴うドキュメント（利用者マニュアルなど）に，上記の著
#         作権表示，この利用条件および下記の無保証規定を掲載すること．
#     (b) 再配布の形態を，別に定める方法によって，TOPPERSプロジェクトに
#         報告すること．
#   (4) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#       害からも，上記著作権者およびTOPPERSプロジェクトを免責すること．
#
#   本ソフトウェアは，無保証で提供されているものである．上記著作権者お
#   よびTOPPERSプロジェクトは，本ソフトウェアに関して，その適用可能性も
#   含めて，いかなる保証も行わない．また，本ソフトウェアの利用により直
#   接的または間接的に生じたいかなる損害に関しても，その責任を負わない．
#
#  @(#) $Id: Makefile.config,v 1.1 2008/04/05 10:25:10 roi Exp $
#
 
#
#  Makefile のプロセッサ依存 (stmcube用)
#

STMCUBE_BSP = $(SRCDIR)/stmcube/Drivers/BSP
STMCUBE_CMS = $(SRCDIR)/stmcube/Drivers/CMSIS
STMCUBE_HAL = $(SRCDIR)/stmcube/Drivers/STM32F7xx_HAL_Driver
STMCUBE_UTL = $(SRCDIR)/stmcube/Utilities
ifeq ($(BOARD),stm32f769discovery_gcc)
STMCUBE_TGT := STM32F769I-Discovery
else
STMCUBE_TGT := STM32746G-Discovery
endif

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(STMCUBE_BSP)/Components/Common -I$(STMCUBE_BSP)/Components/ft5336 \
			-I$(STMCUBE_BSP)/Components/wm8994 -I$(STMCUBE_CMS)/Device/ST/STM32F7xx/Include -I$(STMCUBE_HAL)/Inc \
			-I$(STMCUBE_BSP)/$(STMCUBE_TGT) -I$(STMCUBE_BSP)/Components/rk043fn48h -I$(STMCUBE_UTL)/Fonts

#
#  モニターに関する定義
#
SYSSVC_DIR := $(SYSSVC_DIR):$(STMCUBE_BSP)/$(STMCUBE_TGT):$(STMCUBE_BSP)/Components/ft5336: \
	$(STMCUBE_BSP)/Components/wm8994:$(STMCUBE_BSP)/Components/ft6x06:$(STMCUBE_BSP)/Components/otm8009a:$(STMCUBE_UTL)/Fonts
ifeq ($(STMCUBE_TGT), STM32F769I-Discovery)
SYSSVC_COBJS := $(SYSSVC_COBJS) stm32f769i_discovery.o stm32f769i_discovery_lcd.o stm32f769i_discovery_ts.o \
	stm32f769i_discovery_audio.o 
else
SYSSVC_COBJS := $(SYSSVC_COBJS) stm32746g_discovery.o stm32746g_discovery_lcd.o stm32746g_discovery_ts.o ft5336.o wm8994.o
endif

